version: '3.1'
services:
    app:
        build: ./app
        ports:
            - 5000:5000
        links:
            - db
        depends_on:
            - db 
        command: python -u app.py
        container_name: casino-flask
    db:
        image: mysql:latest
        restart: always
        ports:
            - 32000:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: casino
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        container_name: casino-mysql
